# -*- coding: utf-8 -*-
"""Hybrid_Cipher_Demo2.ipynb

Automatically generated by Colaboratory.


# PROJECT 

# **CRPTOGRAPHY SYSTEM USING VIGENERE CIPHER AND POLYBIUS CIPHER**

### By- SHIVAM VATSHAYAN
"""

#Hello
#How's you ?
#This Hybrid Cipher is developed for Communication security for Army, Secure high level Communication, Message and Data Protection from attackers

"""## Contact me now (vatshayan007@gmail.com) for Code of this Top class project"""

# Python code to implement Cryptographic System 
# First Step is to Give Input to the System

# System 1 : Vigenere Cipher 

# This function generates the 
# key in a cyclic manner until 
# it's length isn't equal to 
# the length of original text 
def generateKey(string, key): 
	key = list(key) 
	if len(string) == len(key): 
		return(key) 
	else: 
		for i in range(len(string) -
					len(key)): 
			key.append(key[i % len(key)]) 
	return("" . join(key))

"""Wait !

This is Only 10% code, for Full code mail me Now. 

Full Project Code is bit longer !!

## Mail me Now (vatshayan007@gmail.com) for full Code  ! 

Let's Discuss about this project. 

Feel Free to Contact me !!
"""
